[package]
name = "fireship-io-crypto-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"
argon2 = "0.4"
rand_core = { version = "0.6", features = ["std"] }
hex = "0.4"